# Generated by Django 5.1 on 2024-08-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_created_at_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
